% Calculates the vector z of BEM unknowns on the nodes (xn,yn).
%
%    met   Geometric element type (1 for linear elements, 2 for quadratic).
%    xn    Nodes' x-coordinates.
%    yn    Nodes' y-coordinates.

function [G,H] = assemble_G_H(met, xn, yn)

    xn(end+1) = xn(1);
    yn(end+1) = yn(1);

    % Total number of BEM nodes
    I = length(xn) - 1;

    % Construction of G and H matrices
    
    H = zeros(I, I);
    G = zeros(I, I);

    if met == 1
  
        % Linear elements
        
        xm = zeros(I, 1);
        ym = zeros(I, 1);
        
        for i = 1:I
            for j = 1:I

                % Mid-point coordinates necessary in findH().
                xm(j) = 0.5 * (xn(j) + xn(j+1));
                ym(j) = 0.5 * (yn(j) + yn(j+1));

                if j == 1 % First column (problem j-1 = I when j = 1)
                    if j == i
                        H(i,j) = 0;
                        G(i,j) =                                        ...
                            findG_lin_s(xn(1), yn(1), xn(2), yn(2))     ...
                            +                                           ...
                            findG_lin_s(xn(I), yn(I), xn(1), yn(1)); 
                    else
                        H(i,j) =                                        ...
                            findH(met, 1, xn(i), yn(i), xn(1), yn(1),   ...
                                          xm(1), ym(1), xn(2), yn(2)  ) ...
                            +                                           ...
                            findH(met, 3, xn(i), yn(i), xn(I), yn(I),   ...
                                          xm(I), ym(I), xn(1), yn(1)  );
                        G(i,j) =                                        ...
                            findG(met, 1, xn(i), yn(i), xn(1), yn(1),   ...
                                          xm(1), ym(1), xn(2), yn(2)  ) ...
                            +                                           ...
                            findG(met, 3, xn(i), yn(i), xn(I), yn(I),   ...
                                          xm(I), ym(I), xn(1), yn(1)  );
                    end
                else % Other columns
                    if j == i
                        H(i,j) = 0;
                        G(i,j) =                                        ...
                            findG_lin_s( xn( j ), yn( j ),              ...
                                         xn(j+1), yn(j+1)  )            ...
                            +                                           ...
                            findG_lin_s( xn(j-1), yn(j-1),              ...
                                         xn( j ), yn( j )  ); 
                    else
                        H(i,j) =                                        ...
                            findH(met, 1, xn( i ), yn( i ),             ...
                                          xn( j ), yn( j ),             ...
                                          xm( j ), ym ( j),             ...
                                          xn(j+1), yn(j+1)  )           ...
                            +                                           ...
                            findH(met, 3, xn( i ), yn( i ),             ...
                                          xn(j-1), yn(j-1),             ...
                                          xm(j-1), ym(j-1),             ...
                                          xn( j ), yn( j )  );
                        G(i,j) =                                        ...
                            findG(met, 1, xn( i ), yn( i ),             ...
                                          xn( j ), yn( j ),             ...
                                          xm( j ), ym( j ),             ...
                                          xn(j+1), yn(j+1)  )           ...
                            +                                           ...
                            findG(met, 3, xn( i ), yn( i ),             ...
                                          xn(j-1), yn(j-1),             ...
                                          xm(j-1), ym(j-1),             ...
                                          xn( j ), yn( j )  );
                    end
                end
            end
            
            % Indirect evaluation of the diagonal influence coefficients
            H(i,i) = -sum(H(i,:));
        end

    
    
    else
        
        disp('Shape function error: supported element type is 1');
    
    end


end